default:
    autoload:
        '': '%paths.base%/../features/bootstrap'
    suites:
        default:
            paths: [ '%paths.base%/../features' ]
            contexts:
                - FeatureContext:
                    parameters:
                        server: "mobile-hub.lambdatest.com"
                        user: "YOUR LT_USERNAME"
                        key: "YOUR LT_ACCESS_KEY"
                        capabilities:
                            # common capabilities added for every test
                            build: "behat-appium-sample"
                            name: "parallel-behat-test"
                            isRealMobile: true
                            app: "YOUR APP URL HERE"
                        environments:
                            # each capability in this list is execute as single test
                            # so to run multiple tests in parallel,
                            # simply define multiple capabilities below and execute the test with
                            # $ php run-parallel.php -c config/<filename>.yml
                        -
                            deviceName: Galaxy S21 Ultra 5G
                            platform: Android
                            platformVersion: 11
                        -
                            deviceName: OnePlus 9 Pro
                            platform: Android
                            platformVersion: 11
                        -
                            deviceName: Redmi 9
                            platform: Android
                            platformVersion: 10

                    